GameConfig:
  max_rounds: 10
  Scores:
    kill: 1
    win: 5
    loss: 0
  Bonifications:
    kill: 300
    win: 3000
    loss: 1500

PhaseTimes:
  buying_duration: 30
  round_duration: 120
  round_end_duration: 5

Player:
  speed: 4.5
  full_health: 100
  initial_money: 800

ShopPrices:
  Guns:
    Ak47: 2700
    M3: 1700
    Awp: 4750
  Mag:
    Ak47: 80
    M3: 8
    Awp: 125
    Glock: 20

ItemsConfig:
  Glock:
    bullets_per_mag: 20
    init_mag_ammo: 20
    init_reserve_ammo: 20
    attack_rate: 6.6
    dir_variation_angle: 0
    bullets_per_attack: 1
    burst_interval: 0
    min_damage: 40
    max_damage: 50
    max_range: 10
    precision: 0.85
    falloff: 0.5
  Ak47:
    bullets_per_mag: 30
    init_mag_ammo: 30
    init_reserve_ammo: 30
    attack_rate: 10
    dir_variation_angle: 0
    bullets_per_attack: 3
    burst_interval: 0.4
    min_damage: 30
    max_damage: 40
    max_range: 20
    precision: 0.7
    falloff: 0.3
  M3:
    bullets_per_mag: 8
    init_mag_ammo: 8
    init_reserve_ammo: 8
    attack_rate: 1.1
    dir_variation_angle: 30
    bullets_per_attack: 8
    burst_interval: 0
    min_damage: 8
    max_damage: 12
    max_range: 5
    precision: 0.3
    falloff: 0
  Awp:
    bullets_per_mag: 10
    init_mag_ammo: 10
    init_reserve_ammo: 10
    attack_rate: 0.68
    dir_variation_angle: 0
    bullets_per_attack: 1
    burst_interval: 0
    min_damage: 100
    max_damage: 100
    max_range: 100
    precision: 1
    falloff: 0
  Knife:
    min_damage: 10
    max_damage: 20
    attack_rate: 5.0
    max_range: 1
    precision: 1
    falloff: 0
  Bomb:
    secs_to_plant: 3
    secs_to_explode: 40
    secs_to_defuse: 5
    damage: 100
    max_range: 15
    precision: 1
    falloff: 0.5
