name: Pre-commit Checks

on:
    pull_request:
        branches: [ main ]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Cache pre-commit
              uses: actions/cache@v3
              with:
                path: ~/.cache/pre-commit
                key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
                restore-keys: |
                        ${{ runner.os }}-pre-commit-

            - name: Install cppcheck
              run: sudo apt-get update && sudo apt-get install -y cppcheck

            - name: Install pre-commit
              run: pip install pre-commit

            - name: Run pre-commit hooks
              run: pre-commit run --all-files
    tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup Cpp
          uses: aminya/setup-cpp@v1
          with:
            compiler: gcc
            cmake: true
            make: true

        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y libopusfile-dev libxmp-dev fluidsynth libfluidsynth-dev libwavpack-dev libfreetype-dev qtbase5-dev qtbase5-dev-tools qt5-qmake

        - name: Run tests
          run: make test
